### ISSUE TITLE
Problem when up server (version 0.15.3)

### ISSUE THREAD

**Issue by mateuspmello** [kolkov/angular-editor#111]
I atualized the version from 0.14.5 to 0.15.3 and I'm having this error message: ERROR in node_modules/@kolkov/angular-editor/lib/angular-editor.service.d.ts(59,46): error TS2370: A rest parameter must be of an array type.

Somebody is having the same problem?

**Comment by kolkov** [comment]
Hi! Provide more details please!

**Comment by sherinmannambeth** [comment]
I am also facing the same problem when running the server.
This is the error that is shown in my terminal
![Capture](https://user-images.githubusercontent.com/25637940/61031946-21fff300-a3de-11e9-8afd-a57b852ac670.PNG)

This error is shown in the console
![image](https://user-images.githubusercontent.com/25637940/61032492-2c6ebc80-a3df-11e9-860f-aa2a7e12151d.png)


I am using the version 0.15.4

**Comment by mateuspmello** [comment]
kolkov, Is just like sherinmannambeth said. The error im my terminal is the same. 
I'm just atualized to 0.15.3. When happned i'm rollback to 0.14.5 and works fine.

**Comment by kolkov** [comment]
@mateuspmello Hi! What version of Angular you are using?

**Comment by mateuspmello** [comment]
From ng version:
![Captura de tela de 2019-07-12 08-37-19](https://user-images.githubusercontent.com/16671718/61125444-38f72180-a480-11e9-83e3-7d19864f5c55.png)

**Comment by kolkov** [comment]
@mateuspmello Thanks! I think than problem in your version of Angular and TS. Please use older version of AngularEditor or upgrade your project to actual version of Angular (7.x.x or 8.x.x).

**Comment by kolkov** [comment]
https://stackblitz.com/edit/angular-editor-wysiwyg this version working on Angular 6.1.0, but without any garanties.

**Comment by kolkov** [comment]
Reopen please if problem persists.
