### ISSUE TITLE
Latest version @kolkov/angular-editor": "^0.18.0" not working with Angular 6 TypeScript version "typescript": "^2.7.2"

### ISSUE THREAD

**Issue by goldel777** [kolkov/angular-editor#119]
The angular-editor does not build with TypeScript 2.7.2 and Angular 6 is not compatible with TypeScript 3.x which is purported to fix the issue.

ERROR in node_modules/@kolkov/angular-editor/lib/angular-editor.service.d.ts(59,46): error TS2370: A rest parameter must be of an array type.
projects/esp-services/esp-editor/src/lib/esp-editor.module.ts(8,47): error TS2304: Cannot find name 'AngularEditorModule'.

i ｢wdm｣: Failed to compile.

Is there a version of Angular Editor that builds with Angular 6?

**Comment by kolkov** [comment]
@goldel777 Yes, latest versions builded with Angular 7.2.15.
For Angular 6.x.x olease use version 0.15.x.

**Comment by kolkov** [comment]
But this example is working with latest version... 
https://stackblitz.com/edit/angular-editor-wysiwyg

**Comment by goldel777** [comment]
Thank You!

I will give that a try

Sent from Yahoo Mail for iPhone


On Wednesday, July 31, 2019, 6:08 PM, Andrey Kolkov <notifications@github.com> wrote:


@goldel777 Yes, latest versions builded with Angular 7.2.15.
For Angular 6.x.x olease use version 0.15.x.
