### ISSUE TITLE
Getting the error when clicking inside the editor

### ISSUE THREAD

**Issue by Giri23082010** [kolkov/angular-editor#29]
Hi, Please help. getting the same error again when I run ng-prod. The below is the version I have installed for the editor.
"@kolkov/angular-editor": "^0.10.6",
and the angular version I am working on is '6.1.4'

ERROR TypeError: Cannot read property 'forEach' of undefined
    at n.triggerBlocks (1.8f5a1e3291901fb90796.js:1)
    at n.exec (1.8f5a1e3291901fb90796.js:1)
    at Object.handleEvent (1.8f5a1e3291901fb90796.js:1)
    at Object.handleEvent (main.4a2c69a6412c69df220e.js:1)
    at Object.handleEvent (main.4a2c69a6412c69df220e.js:1)
    at lr (main.4a2c69a6412c69df220e.js:1)
    at main.4a2c69a6412c69df220e.js:1
    at HTMLDivElement.<anonymous> (main.4a2c69a6412c69df220e.js:1)
    at e.invokeTask (polyfills.ee63c15da1fc0d50acd5.js:1)
    at Object.onInvokeTask (main.4a2c69a6412c69df220e.js:1)

**Comment by kolkov** [comment]
Hi! Try new version please!

**Comment by Giri23082010** [comment]
Hi, I updated to version 0.11.1 and I am still getting the same error and a new error as well. The new one is as below.

main.4a2c69a6412c69df220e.js:1 ERROR TypeError: l.onTextAreaFocus is not a function
    at Object.handleEvent (1.fc1367b18ae854985f51.js:1)
    at Object.handleEvent (main.4a2c69a6412c69df220e.js:1)
    at Object.handleEvent (main.4a2c69a6412c69df220e.js:1)
    at lr (main.4a2c69a6412c69df220e.js:1)
    at main.4a2c69a6412c69df220e.js:1
    at HTMLDivElement.<anonymous> (main.4a2c69a6412c69df220e.js:1)
    at e.invokeTask (polyfills.ee63c15da1fc0d50acd5.js:1)
    at Object.onInvokeTask (main.4a2c69a6412c69df220e.js:1)
    at e.invokeTask (polyfills.ee63c15da1fc0d50acd5.js:1)
    at t.runTask (polyfills.ee63c15da1fc0d50acd5.js:1)
ut @ main.4a2c69a6412c69df220e.js:1
t.handleError @ main.4a2c69a6412c69df220e.js:1
lr @ main.4a2c69a6412c69df220e.js:1
(anonymous) @ main.4a2c69a6412c69df220e.js:1
(anonymous) @ main.4a2c69a6412c69df220e.js:1
e.invokeTask @ polyfills.ee63c15da1fc0d50acd5.js:1
onInvokeTask @ main.4a2c69a6412c69df220e.js:1
e.invokeTask @ polyfills.ee63c15da1fc0d50acd5.js:1
t.runTask @ polyfills.ee63c15da1fc0d50acd5.js:1
t.invokeTask @ polyfills.ee63c15da1fc0d50acd5.js:1
_ @ polyfills.ee63c15da1fc0d50acd5.js:1
m @ polyfills.ee63c15da1fc0d50acd5.js:1
